service: poc-serverless-typescript
 
plugins:
  - serverless-offline
  - serverless-esbuild
 
provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  region: eu-west-1
  stackName: poc-api
  environment:
    NODE_ENV: development
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId: 28ivb3d4wd
    restApiRootResourceId: g6rv8zq0uc

custom:
  headers:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - Language
    - X-Requested-With

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /get-all-users
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true
      - http:
          path: /get-tasks-by-username
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /add-user
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /add-task
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /get-single-task
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /get-single-user
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /get-all-tasks
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /update-user/{id}
          method: put
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /update-task/{id}
          method: put
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /delete-task/{id}
          method: delete
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true 
      - http:
          path: /delete-user/{id}
          method: delete
          cors:
            origin: "*"
            headers: ${self:custom.headers}
          allowCredentials: true
            #test
