service: poc-serverless-typescript
 
plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-plugin-canary-deployments
  # - serverless-aws-alias

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  region: eu-west-1
  stackName: poc-api
  environment:
    NODE_ENV: development
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId: 28ivb3d4wd
    restApiRootResourceId: g6rv8zq0uc
  # aliasStage:
  #   loggingLevel: "OFF"
  #   dataTraceEnabled: false

custom:
  headers:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - Language
    - X-Requested-With

functions:
  api:
    handler: handler.handler
    # aliasStage:
    #   loggingLevel: "OFF"
    #   dataTraceEnabled: false
    events:
      - http:
          path: /get-all-users
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /get-tasks-by-username
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /add-user
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /add-task
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /get-single-task
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /get-single-user
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /get-all-tasks
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /update-user/{id}
          method: put
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /update-task/{id}
          method: put
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /delete-task/{id}
          method: delete
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda
          
      - http:
          path: /delete-user/{id}
          method: delete
          cors:
            origin: "*"
            headers: ${self:custom.headers}
            allowCredentials: true
          integration: lambda

    deploymentSettings: # CodeDeploy configuration
      type: Linear10PercentEvery1Minute # Traffic shifting strategy
      alias: ${self:provider.stage} # Alias to update
      preTrafficHook: preTrafficHookFunction # Optional: Pre-traffic validation Lambda
      postTrafficHook: postTrafficHookFunction # Optional: Post-traffic validation Lambda


  Resources:
    PreTrafficHookFunction:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: ${self:service}-${self:provider.stage}-pre-traffic-hook
        Handler: preTrafficHook.handler
        Runtime: nodejs20.x
        Timeout: 30

    PostTrafficHookFunction:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: ${self:service}-${self:provider.stage}-post-traffic-hook
        Handler: postTrafficHook.handler
        Runtime: nodejs20.x
        Timeout: 30
            #test
# resources:
#   Resources:
#     CurrentLambdaVersionSSM:
#       Type: AWS::SSM::Parameter
#       Properties:
#         Name: /${self:service}/${self:provider.stage}/current-lambda-version
#         Type: String
#         Value: !GetAtt ApiLambdaVersion.Version
#         Description: "Stores the current Lambda version ARN"