service: poc-serverless-typescript

plugins:
  - serverless-offline
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  region: eu-west-1
  stackName: poc-api
  environment:
    NODE_ENV: development
  stage: ${opt:stage, 'test'}
  apiGateway:
    restApiId: 28ivb3d4wd
    restApiRootResourceId: g6rv8zq0uc

#custom:
 # version: v1
  #apiGatewayId: amumt5qu31
#  apiGatewayRestApiRootResourceId: ed4itj2h24
 # serverless-offline:
  #  httpPort: 3000
#  esbuild:
 #   minify: true
  #  exclude: []
   # watch:
    #  pattern: ["./**/*.ts"]

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /get-all-users
          method: get
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /get-tasks-by-username
          method: post
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /add-user
          method: post
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /add-task
          method: post
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /get-single-task
          method: post
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /get-single-user
          method: post
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /get-all-tasks
          method: get
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /update-user/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /update-task/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /delete-task/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
      - http:
          path: /delete-user/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true
          restApiId: amumt5qu31
          restApiRootResourceId: ed4itj2h24
